In [1]:
# https://cs231n.github.io/python-numpy-tutorial/
# 파이썬 넘파이 관련 튜토리얼

In [2]:
import numpy as np 

In [3]:
np.__version__

'1.18.5'

In [4]:
# 구글코랩 + 구글 내드라이브 => 연동
# AWS사용 아마존웹서비스

# 제목을 달아봅시다
## 제목을 달아봅시다
### 제목을 달아봅시다

[naver](http://www.naver.com/)

y=x+10
$y=x+10$

**중요**
__중요__
*중요*
_중요_

- shape : 배열의 구조
- 16*16 컬러사진 -> shape? (28,28,3) 3차원 배열
- 행, 열, 채널 방향이 각각 axis=0, axis=1, axis=2

https://gist.github.com/ihoneymon/652be052a0727ad59601

마크다운 설명서

In [5]:
# shape : 배열의 구조
# 16*16 컬러사진 -> shape? (28,28,3) 3차원 배열
# 행, 열, 채널 방향이 각각 axis=0, axis=1, axis=2

In [6]:
arr=[1,2,3]

In [7]:
a=np.array(arr)

In [8]:
a

array([1, 2, 3])

In [9]:
myarr=np.arange(100000)

In [10]:
myarr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [11]:
mylist=list(range(100000))

In [12]:
mylist

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


mylist에 저장된 요소값에 대해 2배를 한 결과를 mylist2에 저장해라

In [13]:
%time mylist2=[x*2 for x in mylist]

Wall time: 8.98 ms


In [14]:
%time for _ in range(10): mylist2=[x*2 for x in mylist]

Wall time: 79.8 ms


In [15]:
mylist2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

mylist에 저장된 요소값에 대해 2배를 한 결과를 mylist2에 저장해라

In [16]:
%time for _ in range(10): myarr2=myarr*2

Wall time: 998 µs


In [17]:
# n차원 배열 객체? 대량의 데이터 집합을 저장할 수 있는 구조


In [29]:
data=np.random.randn(2,3)

In [31]:
data

array([[-0.50781566,  1.06922753, -0.23657827],
       [ 1.01195539,  1.25175981,  1.29726116]])

In [32]:
data*10

array([[-5.07815664, 10.69227533, -2.36578268],
       [10.11955388, 12.51759812, 12.97261163]])

In [33]:
data+data

array([[-1.01563133,  2.13845507, -0.47315654],
       [ 2.02391078,  2.50351962,  2.59452233]])

In [37]:
# 데이터의 형태를 알수있음
data.shape

(2, 3)

In [38]:
# 데이터 타입을 알수있음
data.dtype

dtype('float64')

In [39]:
data1= [6,7.5,8,0,1]

In [40]:
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [44]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
arr=np.arange(10)
arr.dtype

dtype('int32')

In [51]:
farr=arr.astype(np.float64)
farr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
# 32bit, 64bit
# 정수 32비트
# 1비트 : 0~1, 2비트:0~3,...,16비트:0~42억->-21억~21억, 32비트:922경

In [53]:
farr.dtype

dtype('float64')

In [54]:
arr=farr.astype(np.int32)
arr.dtype

dtype('int32')

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [61]:
# element-wise product
arr*arr

array([[ 1,  4],
       [ 9, 16]])

In [62]:
arr-arr

array([[0, 0],
       [0, 0]])

In [63]:
arr+arr

array([[2, 4],
       [6, 8]])

In [64]:
arr**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [65]:
arr**0.5 # 제곱근

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [74]:
arr=np.arange(10)*2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
arr[5]

10

In [77]:
arr[5:8] # 5번 ~ 7번 index까지 자료를 추출

array([10, 12, 14])

In [78]:
arr[5:8]=20

In [79]:
arr

array([ 0,  2,  4,  6,  8, 20, 20, 20, 16, 18])

In [80]:
arr[4:8]

array([ 8, 20, 20, 20])

In [83]:
ar2=arr[4:8]
ar2

array([ 8, 20, 20, 20])

In [84]:
arr[0]

0

In [85]:
arr[0]=90

In [86]:
arr

array([90,  2,  4,  6,  8, 20, 20, 20, 16, 18])

In [87]:
arr[:]=99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [89]:
# arr이 array구조에서 일반 변수로 바뀜
arr=22
arr

22

In [93]:
arr=np.arange(10)*2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [96]:
arr=np.arange(10,16)

In [97]:
arr

array([10, 11, 12, 13, 14, 15])

In [99]:
arr2d=arr.reshape(2,3)

In [100]:
arr2d

array([[10, 11, 12],
       [13, 14, 15]])

In [103]:
arr2d[0]

array([10, 11, 12])

In [106]:
arr2d[[1]]

array([[13, 14, 15]])

In [107]:
arr2d[0][2]

12

In [109]:
arr2d[0,2]

12

In [112]:
arr=np.arange(12)

In [113]:
arr=arr.reshape(2,3,2)

In [114]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [115]:
arr=np.arange(1,25)
arr=arr.reshape(4,3,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [123]:
# 0~31까지 값을 갖는 array를 생성해서 arr에 저장
arr=np.arange(0,32)
len(arr)

32

In [126]:
arr=arr.reshape(4,2,4)
v=arr.reshape([4,2,4]) # 이렇게 해도됨 
v

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [129]:
v.ndim # 속성 (attribute)
# v.sum() # 함수(function)

3

In [130]:
v.sum(axis=0) # 행방향으로 요소를 더함

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [131]:
v.sum(axis=1) 

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])

In [132]:
v.sum(axis=None)  # default값 모든 요소들의 합

496

In [133]:
# axis=None  모든 요소의 합 -> 1개의 스칼라값
# axis= 1  x축 기준으로 여러개의 row를 한개로 합침
# axis= 2  y축 기준으로  row별로 column 값들을 한개로 합침
# axis= 2  z축 기준으로  column의 depth 값들을 한개로 합침

In [145]:
# 3행 3열 11~ 19까지 값으로 초기화 배열 생성
arr = np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [154]:
arr=arr.reshape(3,3)

In [155]:
arr[0][1:3]

array([12, 13])

In [158]:
arr[2]

array([17, 18, 19])

In [162]:
arr[2,:] 
arr[2,:].shape # 1차원 구조 배열

(3,)

In [160]:
arr[2:,:] # 2차원 구조 배열

array([[17, 18, 19]])

In [168]:
arr[:,0:2]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [169]:
arr[1,0:2]

array([14, 15])

In [170]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [174]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [176]:
np.empty((3,2)) # 3행 2열, 쓰레기값으로 초기화

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [177]:
a=np.array([[1,2,3],[4,5,6]])

In [178]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
b=np.ones_like(a) # a배열과 같은 구조 (2,3)를 1로 초기화한 값으로 생성

In [180]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [182]:
np.__version__

'1.18.5'

In [183]:
np.show_config() # numpy 설치경로

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/82105/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/82105/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/82105/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

In [184]:
Z=np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [185]:
Z.itemsize # 8byte( 64bit float)

8

In [187]:
Z.size # 10개

10

In [188]:
print("%d bytes" %(Z.size *Z.itemsize))

80 bytes


In [191]:
# 크기가 10인 Z배열을 0으로 초기화 -> 5번째 데이터를 1로 변경

Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [192]:
# 10~49 까지 값으로 Z 배열을 초기화( 1차원 벡터)
Z=np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [193]:
Z[:] # 순방향
Z[::] # 순방향
Z[::-1] # 역방향

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [195]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [196]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [197]:
# 0이 아닌 데이터 index 추출
nz=np.nonzero([1,2,0,0,3,0])
nz

(array([0, 1, 4], dtype=int64),)

In [199]:
# 난수 발생 : 0<=범위<1
z=np.random.random((2,3))
z

array([[0.35953186, 0.59100342, 0.60131926],
       [0.01389235, 0.66853152, 0.89186356]])

In [202]:
z.min()

0.013892350825458255

In [201]:
z.max()

0.8918635637588096

In [203]:
z=np.random.random(20)
z

array([0.42256129, 0.92412634, 0.76495787, 0.76307128, 0.7769756 ,
       0.41148309, 0.32551411, 0.94769902, 0.19907685, 0.57291536,
       0.94101518, 0.84106771, 0.21810585, 0.120597  , 0.87565725,
       0.59160078, 0.23067823, 0.20224017, 0.611852  , 0.99005028])

In [204]:
m=z.mean()

In [205]:
print(m)

0.5865622630663883


In [218]:
a=np.ones((10,10))
a[1:9,1:9]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
Z=np.ones((10,10))
Z
Z[1:-1, 1:-1] =0
#1