### 1. 파이썬 연습문제

In [1]:
# - 입력 받은 정수가 음수인지 양수인지 0인지 알려주세요.
num = int(input("정수를 입력하세요 : "))
if num > 0:
   print("양수입니다") 
elif num==0:
    print("0 입니다")
else:
    print("음수입니다")



정수를 입력하세요 : 0
0 입니다


In [2]:
# - 'hello'를 지정한 횟수(0 <= n <= 3)만큼 출력해 보세요.
def hello(n):
    if 0 <= n <= 3:
        print("hello "*n)
    else:
        print("지정된 범위를 벗어났습니다.")
hello(4)

지정된 범위를 벗어났습니다.


In [3]:
# - 0~9사이의 정수를 거꾸로 출력해 보세요.
n=list(range(10))
n[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [4]:
# - 리스트를 출력하면서 앞에 일련번호를 붙여주세요. 
# # 0 2
# # 1 4
# # 2 6
b=[2,4,6]
for i in range(len(b)):
    print(i,":",b[i])

0 : 2
1 : 4
2 : 6


In [5]:
#- 리스트에서 중복 값을 제거해 보세요.
ns = [1, 3, 5, 1, 3, 5, 1, 3, 5]
ns_1=[]
for i in ns:
    if i not in ns_1:
        ns_1.append(i)
ns_1

[1, 3, 5]

### 2. numpy 연습문제

In [6]:
import numpy as np

In [7]:
a = np.random.randint(1, 30, size=(5, 6))
a

array([[28,  3, 20, 27,  7, 16],
       [18, 14, 18,  2, 17, 10],
       [ 4,  1,  3, 22,  6, 12],
       [28, 17, 13, 24, 18, 12],
       [ 5, 19, 13, 24,  2,  4]])

In [8]:
# -전체의 최댓값
a.max()

28

In [9]:
# -각 행의 합
a.sum(axis =1)

array([101,  79,  48, 112,  67])

In [10]:
# -각 행의 최댓값
a.max(axis=1)

array([28, 18, 22, 28, 24])

In [11]:
# -각 열의 평균
a.mean(axis=0)

array([16.6, 10.8, 13.4, 19.8, 10. , 10.8])

In [12]:
# -각 열의 최솟값
a.min(axis=0)

array([4, 1, 3, 2, 2, 4])

In [13]:
# 2)다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
# -이 행렬에서 값 7 을 인덱싱한다.
m[(1,2)]

7

In [15]:
# -이 행렬에서 값 14 을 인덱싱한다.
m[(2,-1)]

14

In [16]:
# -이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1][1:3]

array([6, 7])

In [17]:
# -이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[:,2][1:]

array([ 7, 12])

In [18]:
# -이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:,3:][:2]

array([[3, 4],
       [8, 9]])

In [32]:
# 3) 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.
# (코드를 효율적으로)
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

In [31]:
x=np.hstack([np.zeros((3,3)),np.ones((3,2))])
y=np.arange(10,151,10).reshape(3,5)
z=np.vstack([x,y])
np.tile(z,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [20]:
# 4) 다음 행렬과 같은 배열이 있다.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
# -이 배열에서 3의 배수를 찾아라.
x[x%3==0]


array([ 3,  6,  9, 12, 15, 18])

In [22]:
# -이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [23]:
# -이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x%3==0) & (x%4==1)]

array([9])

In [24]:
# 5) 
# -동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
coin=np.arange(2)
np.random.choice(coin,10)

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [25]:
# -주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
dice=np.arange(1,7)
np.random.choice(dice, 100).mean()

3.25

### 3. iris data 유사 데이터 추출

In [26]:
from sklearn.datasets import load_iris  # 사이킷런 패키지 임포트
iris = load_iris()  # 데이터 로드
iris.data[0, :]  # 첫 번째 꽃의 데이터

array([5.1, 3.5, 1.4, 0.2])

In [27]:
iris.data[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [28]:
distance = np.sqrt(((iris.data[1:len(iris.data)+1] - iris.data[0])**2).sum(axis=1))
distance_min=distance.min()

In [29]:
np.where(distance==distance_min)

(array([16], dtype=int64),)

In [30]:
iris.data[17,:]

array([5.1, 3.5, 1.4, 0.3])